const JWT_DOCTOR_PASSWORD = process.env.JWT_DOCTOR_PASSWORD;
const JWT_PATIENT_PASSWORD = process.env.JWT_PATIENT_PASSWORD;
const JWT_DOCTOR_SECRET = process.env.JWT_DOCTOR_SECRET;
const JWT_PATIENT_SECRET = process.env.JWT_PATIENT_SECRET; 

module.exports = {
    JWT_DOCTOR_PASSWORD,
    JWT_PATIENT_PASSWORD,
    JWT_DOCTOR_SECRET,
    JWT_PATIENT_SECRET
};